name: "Docker"

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed

jobs:
  build:
    name: "Build"
    uses: dockette/.github/.github/workflows/docker.yml@master
    secrets: inherit
    with:
        image: "dockette/vagrant"
        tag: "${{ matrix.item }}"
        context: "${{ matrix.item }}"
    strategy:
      matrix:
        include:
          # Node
          - item: "debian-12"
          - item: "debian-12-systemd"
          - item: "debian-11"
          - item: "debian-11-systemd"
          - item: "debian-10"
          - item: "debian-10-systemd"

      fail-fast: false
